[package]
name = "brickrail-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.1"
bevy_framepace = "0.13.3"
itertools = "0.11.0"
serde_json = "1.0.105"
strum = "0.25.0"
strum_macros = "0.25.2"
