[package]
name = "brickrail-server"
version = "0.1.0"
edition = "2024"

[dependencies]
brickrail-common = { path = "../brickrail-common" }
bevy = { version = "0.19", default-features = false, features = ["serialize"] }
bevy_plugin_graph = { git = "https://github.com/Novakasa/bevy-plugin-graph", rev = "f37ed89ea7eac16d8cd678a7c931c7cc2dccdbd4" }

[dev-dependencies]
bevy = { version = "0.19", default-features = false, features = ["serialize", "bevy_state"] }
petgraph = "0.8"
